"""
1S: ERP Free Edition — Cython transpiler backend.

Emits a `.pyx` source file from a 1S AST.

Compared to the Python backend:
  • `# cython: language_level=3` + optimization directives at the top
  • Type-inference pass annotates variables with `cdef long` / `cdef double`
  • Numeric For-loops use typed counters (no Python int overhead)
  • Functions with numeric-only params/return use `cpdef <type>`
  • Pure-numeric helper functions get `@cython.cfunc` + `@cython.exceptval`
  • `libc.math` is cimported for floor/ceil/fabs/sqrt
  • A top-level `run()` entrypoint wraps executable statements so the
    compiled extension can be driven from a Python script or the CLI

Generated layout
────────────────
  # cython directives + cimports
  from src.runtime import *          ← runtime still imported as Python objects
  cpdef <type> Функція(params):      ← typed cpdef functions (hoisted first)
  ...
  def run():                         ← top-level statements
      ...
  run()                              ← auto-execute on import (mirrors 1C behaviour)
"""
from __future__ import annotations
from ..parser.ast_nodes import (
    Module, Node, VarDecl, ProcedureDef, FunctionDef,
    AssignStmt, ForStmt, ForEachStmt, WhileStmt,
    IfStmt, TryStmt, Identifier, Literal,
)
from .python_backend import PythonTranspiler, CodeWriter, _py_name
from .type_inferencer import TypeInferencer, _LONG, _DOUBLE, _BINT, _OBJECT


# Mapping from inferencer type → Cython type keyword
_CY_TYPE: dict[str, str] = {
    _LONG:   "long",
    _DOUBLE: "double",
    _BINT:   "bint",
    _OBJECT: "object",
}

# Default initial values for typed cdef variables
_CY_INIT: dict[str, str] = {
    _LONG:   "0",
    _DOUBLE: "0.0",
    _BINT:   "0",
}


class CythonTranspiler(PythonTranspiler):
    """
    Translates 1S AST → Cython `.pyx` source.

    Inherits all statement/expression emitters from PythonTranspiler and
    overrides only the parts that need Cython-specific output.
    """

    def __init__(self):
        super().__init__(cython_mode=True)
        self._inferencer = TypeInferencer()
        self._current_func_scope = None    # ScopeTypes while inside a function
        self._current_func_name: str = ""
        self._in_run_wrapper: bool = False  # True when emitting run() body

    # ── Top-level transpile ──────────────────────────────────────────────────

    def transpile(self, module: Module) -> str:
        # Run type inference over the entire module
        self._inferencer.infer(module)
        self._module_scope = self._inferencer.module_scope

        w = self._w
        self._emit_header()

        # ── Hoist all function / procedure definitions ───────────────────
        for node in module.body:
            if isinstance(node, (ProcedureDef, FunctionDef)):
                self._stmt(node)

        # ── Wrap top-level executable code in run() ──────────────────────
        exec_stmts = [n for n in module.body
                      if not isinstance(n, (ProcedureDef, FunctionDef))]

        if exec_stmts:
            w.emit("")
            w.emit("def run():")
            w.indent()
            # Emit cdef for module-level numeric vars inside run()
            self._emit_cdef_block(exec_stmts, self._module_scope)
            self._in_run_wrapper = True
            for node in exec_stmts:
                self._stmt(node)
            self._in_run_wrapper = False
            w.dedent()
            w.emit("")
            w.emit("run()")

        return w.get_code()

    # ── Header ───────────────────────────────────────────────────────────────

    def _emit_header(self):
        w = self._w
        w.emit("# cython: language_level=3")
        w.emit("# cython: boundscheck=False")
        w.emit("# cython: wraparound=False")
        w.emit("# cython: cdivision=True")
        w.emit("# cython: nonecheck=False")
        w.emit("# AUTO-GENERATED by 1S transpiler (Cython mode) — do not edit by hand")
        w.emit("")
        w.emit("import cython")
        w.emit("from libc.math cimport floor, fabs, sqrt, pow as c_pow")
        w.emit("from src.runtime import *")
        w.emit("")

    # ── cdef block helper ────────────────────────────────────────────────────

    def _collect_numeric_vars(self, stmts: list[Node], scope) -> dict[str, str]:
        """
        Walk ALL statements recursively and collect every variable whose
        inferred type is numeric (long / double / bint).

        Cython requires ALL `cdef` declarations at the TOP of a function,
        even if the variable is first used deep inside a nested loop or if.
        This scanner ensures for-loop counters and nested vars are captured.

        Returns ordered dict: {name: cy_type_keyword}
        """
        result: dict[str, str] = {}  # insertion-order preserved (Python 3.7+)

        def _add(name: str) -> None:
            if name in result:
                return
            ty = scope.get(name)
            if ty in _CY_INIT:
                result[name] = _CY_TYPE[ty]

        def _walk(stmts_list: list[Node]) -> None:
            for stmt in stmts_list:
                if isinstance(stmt, VarDecl):
                    for n in stmt.names:
                        _add(n)
                elif isinstance(stmt, ForStmt):
                    # for-loop counter → always long
                    _add(stmt.var)
                    _walk(stmt.body)
                elif isinstance(stmt, ForEachStmt):
                    _walk(stmt.body)
                elif isinstance(stmt, WhileStmt):
                    _walk(stmt.body)
                elif isinstance(stmt, IfStmt):
                    for branch in stmt.branches:
                        _walk(branch.body)
                    if stmt.else_body:
                        _walk(stmt.else_body)
                elif isinstance(stmt, TryStmt):
                    _walk(stmt.body)
                    _walk(stmt.except_body)
                # Note: FunctionDef / ProcedureDef have their own scope
                # handled in _emit_function — don't recurse into them here.

        _walk(stmts)
        return result

    def _emit_cdef_block(self, stmts: list[Node], scope):
        """
        Emit `cdef TYPE name = init` for EVERY numeric variable in the
        function body (including for-loop counters and nested vars).
        Must be called at the TOP of a function/run() body because
        Cython requires all `cdef` at the function top.
        """
        w = self._w
        for name, cy_type in self._collect_numeric_vars(stmts, scope).items():
            init = _CY_INIT.get(
                next((k for k, v in _CY_TYPE.items() if v == cy_type), None), ""
            )
            if init:
                w.emit(f"cdef {cy_type} {_py_name(name)} = {init}")

    # ── Override: VarDecl ────────────────────────────────────────────────────

    def _stmt(self, node: Node):
        w = self._w
        # In function or run() context, cdef is already emitted by _emit_cdef_block;
        # skip the VarDecl entirely (Cython doesn't allow mid-function cdef if we
        # already emitted a block-level cdef).
        if isinstance(node, VarDecl):
            if self._in_function or self._in_run_wrapper:
                scope = self._current_func_scope or self._module_scope
                for name in node.names:
                    ty = scope.get(name)   # _OBJECT for untyped
                    if ty not in _CY_INIT:
                        # object type: still need a Python-object slot
                        w.emit(f"{_py_name(name)} = Undefined")
                    # typed vars already declared by _emit_cdef_block — skip
                return
        super()._stmt(node)

    # ── Override: ForStmt — typed counter ────────────────────────────────────

    # We don't override _stmt for ForStmt because the Python backend already
    # emits `for VAR in range(start, end + 1):` which Cython auto-optimises
    # for typed counters (it detects `range` and avoids Python int allocation).
    # The speedup comes from the cdef declaration of the variable, not the loop
    # syntax.

    # ── Override: function / procedure definitions ────────────────────────────

    def _emit_function(self, name: str, params, body: list[Node],
                       returns: bool, export: bool):
        w = self._w
        func_scope = self._inferencer.scope_for(name)

        # Infer return type
        if returns:
            ret_type = self._inferencer.infer_return_type(body, func_scope)
            cy_ret = _CY_TYPE.get(ret_type, "object")
            if cy_ret == "void":
                cy_ret = "object"  # shouldn't reach here for FunctionDef
        else:
            cy_ret = "void"

        # Format params with Cython types
        typed_params = self._format_typed_params_cython(params, func_scope)

        # Decide cpdef vs cdef:
        # cpdef = callable from Python AND C (best for most 1S funcs)
        # cdef  = C-only (not callable from Python scripts directly)
        defkw = "cpdef"
        if cy_ret == "void":
            w.emit(f"cpdef void {_py_name(name)}({typed_params}):")
        else:
            w.emit(f"cpdef {cy_ret} {_py_name(name)}({typed_params}) except *:")

        w.indent()
        if export:
            w.emit(f"# export: {name}")

        # Save context
        prev_func = self._in_function
        prev_scope = self._current_func_scope
        prev_name = self._current_func_name
        self._in_function = True
        self._current_func_scope = func_scope
        self._current_func_name = name

        # Emit cdef block for local vars FIRST (Cython requires this)
        self._emit_cdef_block(body, func_scope)

        # Emit function body (VarDecls for typed vars are now skipped)
        if not body:
            w.emit("pass")
        else:
            for s in body:
                self._stmt(s)

        if not returns:
            w.emit("return None")

        # Restore context
        self._in_function = prev_func
        self._current_func_scope = prev_scope
        self._current_func_name = prev_name

        w.dedent()
        w.emit("")

    def _format_typed_params_cython(self, params, scope) -> str:
        parts = []
        for p in params:
            ty = scope.get(p.name)
            cy_ty = _CY_TYPE.get(ty, "object")
            if cy_ty == "object":
                # untyped parameter — plain Python style
                if p.default is not None:
                    parts.append(f"{_py_name(p.name)}={self._expr(p.default)}")
                else:
                    parts.append(_py_name(p.name))
            else:
                if p.default is not None:
                    parts.append(f"{cy_ty} {_py_name(p.name)}={self._expr(p.default)}")
                else:
                    parts.append(f"{cy_ty} {_py_name(p.name)}")
        return ", ".join(parts)


# ── Setup.py generator ───────────────────────────────────────────────────────

_SETUP_TEMPLATE = '''\
"""
Auto-generated Cython build script for 1S: ERP Free Edition.
Usage:
    python setup_1s.py build_ext --inplace

Requirements:
    pip install cython setuptools

The compiled extension will appear as:
    {stem}.cpython-<ver>-<platform>.pyd  (Windows)
    {stem}.cpython-<ver>-<platform>.so   (Linux/macOS)
"""
import sys
from pathlib import Path
from setuptools import setup, Extension

try:
    from Cython.Build import cythonize
    from Cython.Compiler import Options
except ImportError:
    print("ERROR: Cython is not installed.  Run:  pip install cython", file=sys.stderr)
    sys.exit(1)

Options.docstrings = False

PYX_FILE = "{pyx_path}"
REPO_ROOT = str(Path(__file__).parent.parent)  # so 'src.runtime' is importable

ext = Extension(
    name="{module_name}",
    sources=[PYX_FILE],
    extra_compile_args=["/O2"] if sys.platform == "win32" else ["-O3", "-march=native"],
)

setup(
    name="1s_compiled",
    ext_modules=cythonize(
        [ext],
        compiler_directives={{
            "language_level": "3",
            "boundscheck":    False,
            "wraparound":     False,
            "cdivision":      True,
            "nonecheck":      False,
        }},
        quiet=False,
    ),
    script_args=["build_ext", "--inplace", "--build-lib", REPO_ROOT],
)
'''

_RUNNER_TEMPLATE = '''\
"""Auto-generated runner for compiled 1S module: {stem}"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))  # project root

try:
    import {module_name}
except ImportError as e:
    print(f"ERROR: Could not import compiled module: {{e}}")
    print("Did you run:  python setup_1s.py build_ext --inplace ?")
    sys.exit(1)
'''


def generate_setup(pyx_path: "Path") -> tuple[str, str]:
    """
    Return (setup_py_source, runner_py_source) strings for the given .pyx path.
    """
    stem = pyx_path.stem
    module_name = stem.replace("-", "_").replace(" ", "_")
    pyx_str = str(pyx_path).replace("\\", "/")

    setup_src = _SETUP_TEMPLATE.format(
        stem=stem,
        pyx_path=pyx_str,
        module_name=module_name,
    )
    runner_src = _RUNNER_TEMPLATE.format(
        stem=stem,
        module_name=module_name,
    )
    return setup_src, runner_src
