"""
1S: ERP Free Edition — Python / Cython transpiler backend
Walks the AST and emits Python 3.10+ source.
"""
from __future__ import annotations
import textwrap
from typing import Optional
from ..parser.ast_nodes import *
from ..lexer.tokens import QUERY_KEYWORDS


# ── Name normalization ───────────────────────────────────────────────────────
# 1C identifiers can be Cyrillic.  We transliterate them so Python can handle
# them — or, better, keep them as-is since Python 3 supports Unicode idents.
# We only mangle names that clash with Python builtins.

_PY_BUILTINS = frozenset({
    "print", "input", "len", "range", "type", "list", "dict", "set",
    "tuple", "str", "int", "float", "bool", "None", "True", "False",
    "open", "id", "next", "iter", "map", "filter", "zip", "all", "any",
    "sum", "max", "min", "abs", "round", "sorted", "reversed",
    "isinstance", "issubclass", "hasattr", "getattr", "setattr",
    "format", "repr", "hash", "object", "property", "staticmethod",
    "classmethod", "super", "Exception", "ValueError", "TypeError",
    "KeyError", "IndexError", "AttributeError",
})

def _py_name(name: str) -> str:
    if name in _PY_BUILTINS:
        return f"_{name}"
    return name


# ── Query transpiler ─────────────────────────────────────────────────────────

def _transpile_query(raw: str) -> str:
    """
    Translate a bilingual 1S query string to a normalized SQL-like string
    that the 1S runtime can execute (via SQLite / pandas).
    Simple word-by-word replacement using QUERY_KEYWORDS table.
    """
    import re
    # Normalize parameter refs: &ИмяПараметра → :ИмяПараметра (SQLite style)
    normalized = re.sub(r"&(\w+)", r":\1", raw)

    def replace_word(match):
        word = match.group(0)
        lower = word.lower().replace(" ", "")
        mapped = QUERY_KEYWORDS.get(lower)
        if mapped:
            return mapped
        return word

    result = re.sub(r"[А-Яа-яA-Za-z_][А-Яа-яA-Za-z0-9_]*", replace_word, normalized)
    return result


# ── Indentation helper ───────────────────────────────────────────────────────

class CodeWriter:
    def __init__(self):
        self._lines: list[str] = []
        self._indent = 0
        self.INDENT_STEP = 4

    def indent(self):
        self._indent += self.INDENT_STEP

    def dedent(self):
        self._indent = max(0, self._indent - self.INDENT_STEP)

    def emit(self, line: str = ""):
        if line.strip():
            self._lines.append(" " * self._indent + line)
        else:
            self._lines.append("")

    def get_code(self) -> str:
        return "\n".join(self._lines)


# ── Main transpiler ──────────────────────────────────────────────────────────

class PythonTranspiler:
    """
    Translates 1S AST → Python 3 source.
    cython_mode=True emits Cython-compatible annotations (WIP).
    """

    def __init__(self, cython_mode: bool = False):
        self.cython_mode = cython_mode
        self._w = CodeWriter()
        self._in_function = False
        self._module_vars: set[str] = set()

    def transpile(self, module: Module) -> str:
        w = self._w
        w.emit("# AUTO-GENERATED by 1S transpiler — do not edit by hand")
        w.emit("from __future__ import annotations")
        w.emit("from src.runtime import *")
        w.emit("")
        # Hoist all function/procedure definitions before executable statements
        # so call order in source doesn't matter (mirrors 1C runtime behaviour).
        for node in module.body:
            if isinstance(node, (ProcedureDef, FunctionDef)):
                self._stmt(node)
        for node in module.body:
            if not isinstance(node, (ProcedureDef, FunctionDef)):
                self._stmt(node)
        return w.get_code()

    # ── Statements ───────────────────────────────────────────────────────────

    def _stmt(self, node: Node):
        w = self._w
        match node:
            case VarDecl(names=names):
                for n in names:
                    w.emit(f"{_py_name(n)} = Undefined")

            case ProcedureDef(name=name, params=params, body=body, export=export):
                self._emit_function(name, params, body, returns=False, export=export)

            case FunctionDef(name=name, params=params, body=body, export=export):
                self._emit_function(name, params, body, returns=True, export=export)

            case AssignStmt(target=target, value=value):
                w.emit(f"{self._expr(target)} = {self._expr(value)}")

            case CallStmt(call=call):
                w.emit(self._expr(call))

            case ReturnStmt(value=value):
                if value is None:
                    w.emit("return")
                else:
                    w.emit(f"return {self._expr(value)}")

            case BreakStmt():
                w.emit("break")

            case ContinueStmt():
                w.emit("continue")

            case RaiseStmt(value=value):
                if value is None:
                    w.emit("raise")
                else:
                    w.emit(f"raise _1SException({self._expr(value)})")

            case GotoStmt(label=label):
                w.emit(f"# GOTO {label} — not supported in Python; restructure loop")

            case LabelStmt(name=name):
                w.emit(f"# LABEL {name}:")

            case IfStmt() as n:
                self._emit_if(n)

            case WhileStmt(condition=cond, body=body):
                w.emit(f"while {self._expr(cond)}:")
                w.indent()
                self._body(body)
                w.dedent()

            case ForStmt(var=var, start=start, end=end, body=body):
                w.emit(f"for {_py_name(var)} in range({self._expr(start)}, {self._expr(end)} + 1):")
                w.indent()
                self._body(body)
                w.dedent()

            case ForEachStmt(var=var, collection=coll, body=body):
                w.emit(f"for {_py_name(var)} in {self._expr(coll)}:")
                w.indent()
                self._body(body)
                w.dedent()

            case TryStmt(body=body, except_body=exc):
                w.emit("try:")
                w.indent()
                self._body(body)
                w.dedent()
                w.emit("except Exception as _exc:")
                w.indent()
                # Inject bilingual error-info helpers so scripts can call them
                w.emit("def ErrorInfo(): return _exc")
                w.emit("def ErrorDescription(): return str(_exc)")
                w.emit("def ИнформацияОбОшибке(): return _exc")
                w.emit("def ОписаниеОшибки(): return str(_exc)")
                self._body(exc)
                w.dedent()

            case PPRegion(name=name, body=body):
                w.emit(f"# region {name}")
                self._body(body)
                w.emit(f"# endregion {name}")

            case PPIfBlock(condition_str=cond, body=body, else_body=else_body):
                w.emit(f"# preprocessor #if {cond} — included:")
                self._body(body)
                if else_body:
                    w.emit("# preprocessor else:")
                    self._body(else_body)

            case _:
                w.emit(f"# Unhandled AST node: {type(node).__name__}")

    def _body(self, stmts: list[Node]):
        if not stmts:
            self._w.emit("pass")
            return
        for s in stmts:
            self._stmt(s)

    def _emit_function(self, name: str, params: list[Param],
                        body: list[Node], returns: bool, export: bool):
        w = self._w
        py_params = self._format_params(params)
        w.emit(f"def {_py_name(name)}({py_params}):")
        w.indent()
        if export:
            w.emit(f'# export: {name}')
        # Declare mutable (by-ref) params as local copies
        for p in params:
            if not p.by_value:
                # In Python everything is by-object-reference; true pass-by-ref
                # needs explicit container trick — for v0.1 we note it
                pass
        prev = self._in_function
        self._in_function = True
        self._body(body)
        if not returns:
            w.emit("return None")
        self._in_function = prev
        w.dedent()
        w.emit("")

    def _format_params(self, params: list[Param]) -> str:
        parts = []
        for p in params:
            if p.default is not None:
                parts.append(f"{_py_name(p.name)}={self._expr(p.default)}")
            else:
                parts.append(_py_name(p.name))
        return ", ".join(parts)

    def _emit_if(self, node: IfStmt):
        w = self._w
        for i, branch in enumerate(node.branches):
            kw = "if" if i == 0 else "elif"
            w.emit(f"{kw} {self._expr(branch.condition)}:")
            w.indent()
            self._body(branch.body)
            w.dedent()
        if node.else_body:
            w.emit("else:")
            w.indent()
            self._body(node.else_body)
            w.dedent()

    # ── Expressions ──────────────────────────────────────────────────────────

    def _expr(self, node: Node) -> str:
        match node:
            case Literal(value=v, kind=k):
                if k == "bool":
                    return "True" if v else "False"
                if k == "null":
                    return "None"
                if k == "undefined":
                    return "Undefined"
                if k == "string":
                    v_str = str(v)
                    if "\n" in v_str:
                        # Multi-line — use triple-quotes
                        safe = v_str.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
                        return f'"""{safe}"""'
                    escaped = v_str.replace("\\", "\\\\").replace('"', '\\"')
                    return f'"{escaped}"'
                if k == "date":
                    # Convert 'YYYYMMDD' → date(YYYY, MM, DD)
                    s = str(v)
                    return f"_parse_date('{s}')"
                return repr(v)

            case Identifier(name=n):
                return _py_name(n)

            case BinOp(op=op, left=left, right=right):
                return f"({self._expr(left)} {op} {self._expr(right)})"

            case UnaryOp(op=op, operand=operand):
                return f"({op} {self._expr(operand)})"

            case Ternary(condition=c, if_true=t, if_false=f):
                return f"({self._expr(t)} if {self._expr(c)} else {self._expr(f)})"

            case CallExpr(callee=callee, args=args):
                arg_str = ", ".join(self._expr(a) for a in args)
                return f"{self._expr(callee)}({arg_str})"

            case MemberExpr(obj=obj, member=m):
                return f"{self._expr(obj)}.{_py_name(m)}"

            case IndexExpr(obj=obj, index=idx):
                return f"{self._expr(obj)}[{self._expr(idx)}]"

            case NewExpr(type_name=t, args=args):
                arg_str = ", ".join(self._expr(a) for a in args)
                return f"{_py_name(t)}({arg_str})"

            case QueryExpr(raw_text=raw):
                sql = _transpile_query(raw)
                escaped = sql.replace('"', '\\"')
                return f'_Query("{escaped}")'

            case _:
                return f"# unknown_expr({type(node).__name__})"
