# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: nonecheck=False
# AUTO-GENERATED by 1S transpiler (Cython mode) — do not edit by hand

import cython
from libc.math cimport floor, fabs, sqrt, pow as c_pow
from src.runtime import *


def run():
    cdef long A = 0
    cdef long B = 0
    cdef long Tmp = 0
    cdef long K = 0
    cdef long Mod = 0
    cdef long Sum = 0
    cdef long N = 0
    cdef long MaxN = 0
    cdef long PrimeCount = 0
    cdef long M = 0
    cdef long Steps = 0
    cdef long Hits = 0
    cdef long Seed = 0
    cdef double X = 0.0
    cdef double Y = 0.0
    Message("══════════════════════════════════════════════════════════════")
    Message("  CYTHON PERFORMANCE DEMO  ·  1S: ERP  ·  English")
    Message("══════════════════════════════════════════════════════════════")
    Message("")
    A = 0
    B = 1
    Tmp = 0
    Mod = 1000000007
    T0 = TimeNow()
    for K in range(1, 1000000 + 1):
        Tmp = ((A + B) % Mod)
        A = B
        B = Tmp
    Ms1 = Round(((TimeNow() - T0) * 1000), 2)
    Message("── Test 1: 1,000,000 Fibonacci iterations ────────────────────────")
    Message(StrTemplate("  Result pair (A,B): (%1, %2)   Python: %3 ms", A, B, Ms1))
    Message("  Cython: cdef long A,B,Tmp,K → expected ~0.5-2 ms (10-50x)")
    Message("")
    Sum = 0
    T0 = TimeNow()
    for N in range(1, 500000 + 1):
        Sum = (Sum + (N * N))
    Ms2 = Round(((TimeNow() - T0) * 1000), 2)
    Message("── Test 2: Σ(N²) for N=1..500,000 ──────────────────────────────")
    Message(StrTemplate("  Result: %1   Python: %2 ms", Sum, Ms2))
    Message("  Cython: cdef long Sum=0,N=0 → expected ~0.3-1 ms (15-60x)")
    Message("")
    MaxN = 100000
    PrimeCount = 0
    Sieve = Array()
    for K in range(0, MaxN + 1):
        Sieve.Add(True)
    T0 = TimeNow()
    for K in range(2, MaxN + 1):
        if (Sieve[K] == True):
            PrimeCount = (PrimeCount + 1)
            M = (K + K)
            while (M <= MaxN):
                Sieve.Set(M, False)
                M = (M + K)
    Ms3 = Round(((TimeNow() - T0) * 1000), 2)
    Message("── Test 3: Sieve of Eratosthenes to 100,000 ──────────────────────")
    Message(StrTemplate("  Primes found: %1   Python: %2 ms", PrimeCount, Ms3))
    Message("  Cython: cdef long MaxN=0,PrimeCount=0,K=0,M=0 → ~1-3 ms (10-30x)")
    Message("")
    Steps = 0
    Hits = 0
    Seed = 123456789
    T0 = TimeNow()
    for K in range(1, 100000 + 1):
        Seed = (((Seed * 1664525) + 1013904223) % 2147483647)
        X = (Seed / 2147483647.0)
        Seed = (((Seed * 1664525) + 1013904223) % 2147483647)
        Y = (Seed / 2147483647.0)
        if (((X * X) + (Y * Y)) <= 1.0):
            Hits = (Hits + 1)
        Steps = (Steps + 1)
    Ms4 = Round(((TimeNow() - T0) * 1000), 2)
    Pi = ((Hits / Steps) * 4)
    Message("── Test 4: Monte Carlo π (100,000 points) ────────────────────────")
    Message(StrTemplate("  π ≈ %1   Python: %2 ms", Format(Pi, "ЧДЦ=6"), Ms4))
    Message("  Cython: cdef double X=0.0,Y=0.0 → ~1-4 ms (8-20x)")
    Message("")
    TotalMs = Round((((Ms1 + Ms2) + Ms3) + Ms4), 1)
    Message("── Summary & compilation instructions ────────────────────────────")
    Message(StrTemplate("  Total Python time: %1 ms", TotalMs))
    Message("  Expected Cython:   ~3-10 ms  (overall 5-20x faster)")
    Message("")
    Message("  Step 1 — Generate .pyx:")
    Message("    python -m src.cli cython-gen  examples/demo_cython_perf_en.1s")
    Message("    --> creates: examples/demo_cython_perf_en.pyx")
    Message("")
    Message("  Step 2 — Compile (requires gcc / clang / MSVC):")
    Message("    python -m src.cli cython-build examples/demo_cython_perf_en.1s --run")
    Message("    --> pip install cython  (if not installed)")
    Message("")
    Message("  Cython types inferred for this script:")
    Message("    cdef long  A,B,Tmp,K,Sum,N,MaxN,PrimeCount,M,Steps,Hits,Seed")
    Message("    cdef double X, Y, Pi")
    Message("    (LCG inlined in loop body -> no function call overhead)")
    Message("")
    Message("══════════════════════════════════════════════════════════════")
    Message("  1S: ERP — Cython Performance Demo (English) — completed")
    Message("══════════════════════════════════════════════════════════════")

run()