# cython: language_level=3
# cython: boundscheck=False
# cython: wraparound=False
# cython: cdivision=True
# cython: nonecheck=False
# AUTO-GENERATED by 1S transpiler (Cython mode) — do not edit by hand

import cython
from libc.math cimport floor, fabs, sqrt, pow as c_pow
from src.runtime import *

cpdef void ПоказатьПриветствие(Текст):
    Сообщить(Текст)
    return None

cpdef long Square(long N) except *:
    return (N * N)


def run():
    cdef long А = 0
    cdef double X = 0.0
    cdef long Age = 0
    Приветствие = Undefined
    Приветствие = "Привет, мир!"
    Greeting = Undefined
    Greeting = "Hello, World!"
    for А in range(1, 5 + 1):
        if (А == 1):
            Сообщить("Один")
        elif (А == 2):
            Сообщить("Два")
        else:
            Сообщить(("Больше двух: " + Строка(А)))
    Fruits = Undefined
    Fruits = Array()
    Fruits.Add("Apple")
    Fruits.Add("Banana")
    Fruits.Add("Cherry")
    for Fruit in Fruits:
        Message(Fruit)
    try:
        X = (1 / 0)
    except Exception as _exc:
        def ErrorInfo(): return _exc
        def ErrorDescription(): return str(_exc)
        def ИнформацияОбОшибке(): return _exc
        def ОписаниеОшибки(): return str(_exc)
        Message(("Division error caught: " + ErrorDescription()))
    IsAdult = Undefined
    Age = 20
    IsAdult = ("Adult" if (Age >= 18) else "Minor")
    Message(IsAdult)
    ПоказатьПриветствие(Приветствие)
    Message(Greeting)
    Message(("5² = " + String(Square(5))))

run()