# AUTO-GENERATED by 1S transpiler — do not edit by hand
from __future__ import annotations
from src.runtime import *

def ПоказатьПриветствие(Текст):
    Сообщить(Текст)
    return None

def Square(N):
    return (N * N)

Приветствие = Undefined
Приветствие = "Привет, мир!"
Greeting = Undefined
Greeting = "Hello, World!"
for А in range(1, 5 + 1):
    if (А == 1):
        Сообщить("Один")
    elif (А == 2):
        Сообщить("Два")
    else:
        Сообщить(("Больше двух: " + Строка(А)))
Fruits = Undefined
Fruits = Array()
Fruits.Add("Apple")
Fruits.Add("Banana")
Fruits.Add("Cherry")
for Fruit in Fruits:
    Message(Fruit)
try:
    X = Undefined
    X = (1 / 0)
except Exception as _exc:
    def ErrorInfo(): return _exc
    def ErrorDescription(): return str(_exc)
    def ИнформацияОбОшибке(): return _exc
    def ОписаниеОшибки(): return str(_exc)
    Message(("Division error caught: " + ErrorDescription()))
IsAdult = Undefined
Age = Undefined
Age = 20
IsAdult = ("Adult" if (Age >= 18) else "Minor")
Message(IsAdult)
ПоказатьПриветствие(Приветствие)
Message(Greeting)
Message(("5² = " + String(Square(5))))